"""Initial schema

Revision ID: 54ec87992e45
Revises: 
Create Date: 2026-04-08 16:37:57.579518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54ec87992e45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('n_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('p_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('k_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('micronutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.Enum('kg', 'liter', name='unitenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('formulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_crop', sa.String(), nullable=True),
    sa.Column('growth_stage', sa.String(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_id', sa.UUID(), nullable=False),
    sa.Column('price_vnd', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formula_id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('locked_price_vnd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formula_ingredients')
    op.drop_table('price_history')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fertilizers')
    # ### end Alembic commands ###
