"""Add area to formula

Revision ID: e8fc232d5387
Revises: 54ec87992e45
Create Date: 2026-04-08 17:08:14.809208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fc232d5387'
down_revision: Union[str, None] = '54ec87992e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'area')
    # ### end Alembic commands ###
